# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumTesting():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumTesting(self):
    self.driver.get("https://sagarvedbairwa.github.io/CS303/")
    self.driver.set_window_size(1920, 1016)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "docs").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.ID, "inputFeet").click()
    self.driver.find_element(By.ID, "inputFeet").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > #inputFeet").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > #inputFeet").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(5) > #inputFeet").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(5) > #inputFeet").send_keys("1")


